variables:
  CI: "true"

default:
  image: michielc/mcmr_tester:latest

Julia latest:
  coverage: /Test coverage (\d+\.\d+%)/
  script:
    - .ci/run_test.sh
  after_script:
    - .ci/get_coverage.sh
pages:
  script:
    - .ci/gen_docs.sh dev
  artifacts:
    paths:
      - public
  only:
    - main
.benchmark-main:
  stage: deploy
  script:
    - git remote -v
    - git fetch origin main
    - julia benchmark/run_benchmarks.jl origin/main
  except:
    - main
.benchmark-version:
  stage: deploy
  script:
    - VERSION=`julia -e "using TOML; println(TOML.parsefile(\"Project.toml\")[\"version\"])"`
    - git fetch origin v${VERSION}
    - julia benchmark/run_benchmarks.jl v${VERSION}
  only:
    - main

