name = "MRSimulator"
uuid = "eac06e4d-a854-4bf6-b44f-54c98b0401d1"
authors = ["Michiel Cottaar <Mmichiel.cottaar@ndcn.ox.ac.uk>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
